apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-router
  template:
    metadata:
      labels:
        app: alert-router
    spec:
      containers:
        - name: alert-router
          image: nginx:1.7.9
